### PR TITLE
Add watchos 32Bit support

### PR DESCRIPTION
**Pull request by hfhbd**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Do you actually need these? Or are they for completeness?

**Comment by hfhbd** [comment]
Unfortunately, the S3 uses 32 bit and this processor is used in the Apple Watch 3, which was sold until September 2022, for stupid reasons... https://en.wikipedia.org/wiki/Apple_Watch#Support

**Comment by hfhbd** [comment]
Any plans to publish these targets, eg in `0.6.1`?

**Comment by JakeWharton** [comment]
Done

**Pull request merged**
